### ISSUE TITLE
Move to std::shared_ptr

### ISSUE THREAD

**Issue by PepMS** [PepMS/multicopter-mpc#63]
Due to its close dependency on Crocoddyl, the library started using boost smart pointers.

Since the minimum required C++ version for Eagle-MPC is C++11, these could be moved to std and only use the boost library when strictly necessary.

**Comment by joansola** [comment]
Totally agree

**Comment by PepMS** [comment]
This is not going to be possible since Crocoddyl uses boost::shared_ptrs.
